// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.GDPData
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("countryName")]
        public string CountryName { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("year")]
        public long? Year { get; set; }

        [JsonProperty("gdp")]
        public long? Gdp { get; set; }

        [JsonProperty("gdpFormatted")]
        public string GdpFormatted { get; set; }

        [JsonProperty("gdpGrowth")]
        public double? GdpGrowth { get; set; }

        [JsonProperty("gdpPerCapita")]
        public long? GdpPerCapita { get; set; }

        [JsonProperty("count")]
        public long? Count { get; set; }

        [JsonProperty("years")]
        public Year[] Years { get; set; }
    }

    public partial class Year
    {
        [JsonProperty("year")]
        public long? YearYear { get; set; }

        [JsonProperty("gdp")]
        public long? Gdp { get; set; }

        [JsonProperty("gdpFormatted")]
        public string GdpFormatted { get; set; }

        [JsonProperty("gdpGrowth")]
        public double? GdpGrowth { get; set; }

        [JsonProperty("gdpPerCapita")]
        public long? GdpPerCapita { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
